### ISSUE TITLE
Thread object has not attribute isAlive()

### ISSUE THREAD

**Issue by Morg42** [And3rsL/Deebotozmo#19]
The current version is configured, on trying to call up the statuses, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Volumes/McDaten/sh/src/github/Deebotozmo/deebotozmo/cli.py", line 216, in <module>
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Volumes/McDaten/sh/src/github/Deebotozmo/deebotozmo/cli.py", line 150, in statuses
    dologin()
  File "/Volumes/McDaten/sh/src/github/Deebotozmo/deebotozmo/cli.py", line 213, in dologin
    vacbot.connect_and_wait_until_ready()
  File "/Volumes/McDaten/sh/src/github/Deebotozmo/deebotozmo/__init__.py", line 276, in connect_and_wait_until_ready
    self.iotmq.schedule(30, self.send_ping)
  File "/Volumes/McDaten/sh/src/github/Deebotozmo/deebotozmo/ecovacsiotmq.py", line 84, in schedule
    if not self.scheduler_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```

I got a similar error, where the thread was still existent when I tested for its existence, but just after that when trying to call isAlive, it was already gone. Don't know what happens here, though...?

**Comment by Morg42** [comment]
Okay, actually, this was trivial... or was ist?

Current Python documentation says that the Thread-class has a method called `is_alive()`, not `isAlive()`. Not sure if this was changed recently? I'm on python 3.9... will create PR
