### ISSUE TITLE
Auth error since today but on first try it works

### ISSUE THREAD

**Issue by hawkeyexp** [And3rsL/Deebotozmo#22]
Hi, since today i get this error:

`deebotozmo ERROR    call to user/login failed with {'code': '0002', 'msg': '校验异常', 'time': 1609686299744}
Traceback (most recent call last):
  File "/usr/local/bin/deebotozmo", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deebotozmo/cli.py", line 150, in statuses
    dologin()
  File "/usr/local/lib/python3.7/dist-packages/deebotozmo/cli.py", line 207, in dologin
    config['country'], config['continent'], verify_ssl=config['verify_ssl'])
  File "/usr/local/lib/python3.7/dist-packages/deebotozmo/__init__.py", line 54, in __init__
    ('password', self.encrypt(password_hash)))
  File "/usr/local/lib/python3.7/dist-packages/deebotozmo/__init__.py", line 102, in __call_main_api
    json['code'], json['msg'], function, args))
RuntimeError: failure code 0002 (校验异常) for call user/login and parameters (('account', 'xxxxxxxxxx'), ('password', 'xxxxxxxxxx'))
`
I modded the account and pass for this post ...

But the intersting thing:
It works one time after a frech creating config - after this successfull attempt it will fail (tried with command statuses)

It was working now for weeks - i think it must be something on ecovacs side ...

Version: 1.7.2 installed via pip3

**Comment by edenhaus** [comment]
V2 was just released with a lot of refactoring. Therefore I will close this issue.
If the issue still exists open please a new issue
