### ISSUE TITLE
Error reading http response

### ISSUE THREAD

**Issue by mielune** [And3rsL/Deebotozmo#23]
Hi,

It seems thath something changed from they servers : 

I did the config:
```
deebotozmo createconfig
Ecovacs app email: xxx@yyy.com
Ecovacs app password: xxxxxxx
your two-letter country code [fr]: 
your two-letter continent code [eu]: 
Verify SSL for API requests [True]: False   (also tried with True)
overwrite existing config? [y/N]: y
Config saved.
```

And I have this errors ( and the same in HA logs):
```
$deebotozmo components

Traceback (most recent call last):
  File "/home/laurent/nebula/tmp/deebot/bin/deebotozmo", line 8, in <module>
    sys.exit(cli())
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/deebotozmo/cli.py", line 171, in components
    vacbot.refresh_components()
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/deebotozmo/__init__.py", line 499, in refresh_components
    self.exc_command('GetCleanLogs')
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/deebotozmo/__init__.py", line 619, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/deebotozmo/__init__.py", line 623, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/deebotozmo/ecovacsiotmq.py", line 113, in send_command
    self._handle_ctl_api(action, self.CallCleanLogsApi(self.jsonRequestHeaderCleanLogs(action, recipient) ,verify_ssl=self.verify_ssl ))
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/deebotozmo/ecovacsiotmq.py", line 222, in _handle_ctl_api
    s(resp)
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/deebotozmo/__init__.py", line 272, in _handle_ctl
    getattr(self, method)(ctl)
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/deebotozmo/__init__.py", line 316, in _handle_clean_logs
    self.last_clean_image = response[0]['imageUrl']
IndexError: list index out of range
```

ANd with command stats : 

```
$deebotozmo stats

Traceback (most recent call last):
  File "/home/laurent/nebula/tmp/deebot/bin/deebotozmo", line 8, in <module>
    sys.exit(cli())
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/laurent/nebula/tmp/deebot/lib/python3.8/site-packages/deebotozmo/cli.py", line 163, in stats
    print("Stats Cid: " + vacbot.stats_cid)
TypeError: can only concatenate str (not "NoneType") to str
```

I hope this can help and if you need some help to test something ...

**Comment by mielune** [comment]
Using a DEEBOT OZMO 930

**Comment by mikelauff** [comment]
I'm seeing this same result. I'm using a DEEBOT N79S/SE

**Comment by edenhaus** [comment]
> Using a DEEBOT OZMO 930

See https://github.com/And3rsL/Deebotozmo/issues/28

> I'm seeing this same result. I'm using a DEEBOT N79S/SE

I think also the N79 is using XMPP but not sure...
