### ISSUE TITLE
spotarea clean need syntax format

### ISSUE THREAD

**Issue by sujitrp** [And3rsL/Deebotozmo#24]
Hi 
This is great work and made easy for me and my family to run ecovacs . I used openhab to ease the interface . 
All working good . only not able to trigger the spotarea . I am not able to understand the syntax. 

Room Set up : getroom output 
    0 Living Room
    2 Lounge
    1 Dining Room
    4 Kitchen
Now I am trying
deebotozmo spotarea 4  -- Not working 
deebotozmo spotarea "4"   -- not working 
deebotozmo spotarea "4" cleanings -- not working 

Over help section : Cleans provided rooms(s), ex: "0,1" | Use GetRooms to see saved number

but my bad I am not able to understand exactly what it is looking for @ spotarea

Cansomeone help me with correct syntax and one example ?

**Comment by And3rsL** [comment]
Does it give to you any error?

Can you try with --debug option and see what it does say?

**Comment by sujitrp** [comment]
Hi Andrea,
Output with following 3 debug options

deebotozmo spotarea 4 --debug
deebotozmo spotarea "4" --debug
deebotozmo spotarea "4" cleanings --debug

`
openhabian@PI100:~ $ deebotozmo spotarea 4 --debug
Traceback (most recent call last):
  File "/home/openhabian/.local/bin/deebotozmo", line 10, in <module>
    sys.exit(cli())
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/cli.py", line 106, in SpotArea
    vacbot.SpotArea(rooms, cleanings)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 605, in SpotArea
    self.exc_command('clean', {'act': 'start', 'content': str(area), 'count': int(cleanings), 'type': 'spotArea'})
ValueError: invalid literal for int() with base 10: '--debug'
openhabian@PI100:~ $ deebotozmo spotarea "4" --debug
Traceback (most recent call last):
  File "/home/openhabian/.local/bin/deebotozmo", line 10, in <module>
    sys.exit(cli())
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/cli.py", line 106, in SpotArea
    vacbot.SpotArea(rooms, cleanings)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 605, in SpotArea
    self.exc_command('clean', {'act': 'start', 'content': str(area), 'count': int(cleanings), 'type': 'spotArea'})
ValueError: invalid literal for int() with base 10: '--debug'
openhabian@PI100:~ $ deebotozmo spotarea "4" cleanings --debug
Usage: deebotozmo [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...

Options:
  --debug / --no-debug
  --help                Show this message and exit.

Commands:
  charge         Returns to charger
  clean          Auto clean
  components     Get robot components life span
  createconfig   logs in with specified email; run this first
  customarea     Cleans provided area(s), ex: "-602,1812,800,723"
  dodebug        debug function, do not use :)
  exportlivemap  Get robot map and save it [filepath ex:...
  getcleanlogs   Get Clean Logs
  getrooms       Get saved rooms
  pause          pause the robot
  playsound      Play welcome sound
  resume         Resume the robot
  setfanspeed    Set Clean Speed
  setwaterlevel  Set Water Level
  spotarea       Cleans provided rooms(s), ex: "0,1" | Use GetRooms to see...
  stats          Get stats
  statuses       Get robot statuses [Status,Battery,FanSpeed,WaterLevel]
openhabian@PI100:~ $

`

**Comment by sujitrp** [comment]
Hi Tried these 4 options nothing worked 
deebotozmo  --debug spotarea "4" cleanings
deebotozmo  --debug spotarea "4" CLEANINGS
deebotozmo  --debug spotarea 4 CLEANINGS
deebotozmo  --debug spotarea 4 cleanings

Debug Output : 


`openhabian@PI100:~ $ deebotozmo  --debug spotarea "4" cleanings
deebotozmo DEBUG    Setting up EcoVacsAPI
deebotozmo DEBUG    calling main api user/login with (('account', '2VoRZE4SVooPgpu5nZ9tqVlIJgZceCDdGN4x10P73eI3UJ/VdTY+ZT8fJVCwksk7SMi6QR9aW9PHkB+9nZwpV37ZabhtVQ+QQSB8l00YpPbCPK9yGAJYsVQtbSRnWUaM63yJirXe9wCfPKNAucz6uhV69KQHoa0SncMYXoedMDg='), ('password', 'n5+lTu490Pnjx1hjffznZdpvxRwx/pj8jiq8ZW2AFqjbkkNbursX21SmFOfmZ6fGAeqOju1XoXKul/EjqwfYRXIOuXb/jNXmLmXLID2Bvt8URhtI8VZGc7TNxTtG/81kPHgETWn55Itv1CuyHkisKEw9CJRVeK6oYFQh5lmv70M='))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1610988695744, 'data': {'uid': 'XXXXXXXXXXXXXXXXXXXX', 'username': 'YYYYYYY', 'email': 'YYYYYYY@xyz.com', 'country': 'in', 'accessToken': 'ghdjftgsjhfgsjhgeuyfxckjvhxcuvxdvjhgh'}}
deebotozmo DEBUG    calling main api user/getAuthCode with (('uid', 'XXXXXXXXXXXXXXXXXXXX'), ('accessToken', 'ghdjftgsjhfgsjhgeuyfxckjvhxcuvxdvjhgh'))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1610988696358, 'data': {'authCode': 'in_f901c552ecb0329ea71449b68209e608', 'ecovacsUid': 'ghdjftgsjhfgsjhgeuyfxckjvhxcuvxdvjhgh'}}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'userId': 'ghdjftgsjhfgsjhge', 'resource': '57ec159e', 'token': '1986c3a00e1742f3b21bf19bf8a2c44a', 'last': 604800000}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'devices': [{'did': '0cb98872-0297-409e-b9b7-d5e0f1b00eb8', 'name': 'E093LCQP9B09HEJJ0244', 'class': 'yna5xi', 'resource': '3N0R', 'nick': 'eccho', 'company': 'eco-ng', 'bindTs': 1606409485695}]}
deebotozmo.ecovacsiotmq DEBUG    EcoVacsMQTT - Connected with result code 0
deebotozmo.ecovacsiotmq DEBUG    EcoVacsMQTT - Subscribing to all
deebotozmo DEBUG    [Command] SpotArea content=4 count=cleanings
Traceback (most recent call last):
  File "/home/openhabian/.local/bin/deebotozmo", line 10, in <module>
    sys.exit(cli())
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/cli.py", line 106, in SpotArea
    vacbot.SpotArea(rooms, cleanings)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 605, in SpotArea
    self.exc_command('clean', {'act': 'start', 'content': str(area), 'count': int(cleanings), 'type': 'spotArea'})
ValueError: invalid literal for int() with base 10: 'cleanings'
openhabian@PI100:~ $ deebotozmo  --debug spotarea "4" CLEANINGS
deebotozmo DEBUG    Setting up EcoVacsAPI
deebotozmo DEBUG    calling main api user/login with (('account', 'g79fZ6ZSaGpKAWn7EsKFloIQ9yFGExGWFQBk0HcMZdtW7i/d+yfpe176IYrXp3GuccDLXZW7ckWLQ66TQSp3KC2/IPuyAW7lWm775n9t7JVbdfCCRclHmx8OoHnaTVYlNOInUpMREmuTowR8lFeo5jnLEPCK40eXO6beh/NNPLk='), ('password', 'fHT4lbdeVg8e5LhXx3QejjtN6BPGh4Flkn32MmhScXWLdYxxxCPJdiL2a49mcuGQos5EX0/QR3gkl4PmWzupAj7tJcTb4dG+sZhiymACdeWqfECuy5KhDTIJv59bsV6OGOPWqcF9mfjUC/82efFDDCN0IYLPmNMNM0gHf208Sig='))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1610988742573, 'data': {'uid': 'XXXXXXXXXXXXXXXXXXXX', 'username': 'YYYYYYY', 'email': 'YYYYYYY@xyz.com', 'country': 'in', 'accessToken': 'ae5c4b3be1eea6fda7b289a56def75cc'}}
deebotozmo DEBUG    calling main api user/getAuthCode with (('uid', 'XXXXXXXXXXXXXXXXXXXX'), ('accessToken', 'ae5c4b3be1eea6fda7b289a56def75cc'))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1610988743175, 'data': {'authCode': 'in_79a106974357cd27ced5592a1487fe70', 'ecovacsUid': 'ghdjftgsjhfgsjhgeuyfxckjvhxcuvxdvjhgh'}}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'userId': 'ghdjftgsjhfgsjhge', 'resource': '57ec159e', 'token': '26d360ce819d48348e895b77d690f413', 'last': 604800000}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'devices': [{'did': '0cb98872-0297-409e-b9b7-d5e0f1b00eb8', 'name': 'E093LCQP9B09HEJJ0244', 'class': 'yna5xi', 'resource': '3N0R', 'nick': 'eccho', 'company': 'eco-ng', 'bindTs': 1606409485695}]}
deebotozmo.ecovacsiotmq DEBUG    EcoVacsMQTT - Connected with result code 0
deebotozmo.ecovacsiotmq DEBUG    EcoVacsMQTT - Subscribing to all
deebotozmo DEBUG    [Command] SpotArea content=4 count=CLEANINGS
Traceback (most recent call last):
  File "/home/openhabian/.local/bin/deebotozmo", line 10, in <module>
    sys.exit(cli())
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/cli.py", line 106, in SpotArea
    vacbot.SpotArea(rooms, cleanings)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 605, in SpotArea
    self.exc_command('clean', {'act': 'start', 'content': str(area), 'count': int(cleanings), 'type': 'spotArea'})
ValueError: invalid literal for int() with base 10: 'CLEANINGS'
openhabian@PI100:~ $ deebotozmo  --debug spotarea 4 CLEANINGS
deebotozmo DEBUG    Setting up EcoVacsAPI
deebotozmo DEBUG    calling main api user/login with (('account', 'RH8cB8FLSx1euSG09iJa73Po4pz8/eAtGmn6SZAdhSJrQ/q8AViknzYqRds8gJ5usD6syesQh9wqvsMlCPqzlNzTeuWmk4h8VEf4CahbHGy4bjrRR6oPmagnP3eoHD7LJ//I4ji7V9X01zD3vjA6zL4v/IEZtVgcmJBPuWGxYX0='), ('password', 'SOnzJGp9Y8q2Lnyxk19p6kxAfRtEm8gCeiNhh4bqjz6Zno1pKF5dosCrnqCbYVxbqO1oh/II43tiu8LXvobhgoQ0REjo6x1sBrNuH7exMGClGsOY5PFI8XAAnZPjlCXuNZ/uO/WsjHDelD/Qjuxp72zLZU0EACUaJNuyGsPkPHE='))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1610988756362, 'data': {'uid': 'XXXXXXXXXXXXXXXXXXXX', 'username': 'YYYYYYY', 'email': 'YYYYYYY@xyz.com', 'country': 'in', 'accessToken': '46188bcddba66fbd1244c4f05949becd'}}
deebotozmo DEBUG    calling main api user/getAuthCode with (('uid', 'XXXXXXXXXXXXXXXXXXXX'), ('accessToken', '46188bcddba66fbd1244c4f05949becd'))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1610988756981, 'data': {'authCode': 'in_8f2162a9dbd356f3ba7a641158785c0b', 'ecovacsUid': 'ghdjftgsjhfgsjhgeuyfxckjvhxcuvxdvjhgh'}}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'userId': 'ghdjftgsjhfgsjhge', 'resource': '57ec159e', 'token': 'f222a3a59a714d21b0be99db5399cacc', 'last': 604800000}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'devices': [{'did': '0cb98872-0297-409e-b9b7-d5e0f1b00eb8', 'name': 'E093LCQP9B09HEJJ0244', 'class': 'yna5xi', 'resource': '3N0R', 'nick': 'eccho', 'company': 'eco-ng', 'bindTs': 1606409485695}]}
deebotozmo.ecovacsiotmq DEBUG    EcoVacsMQTT - Connected with result code 0
deebotozmo.ecovacsiotmq DEBUG    EcoVacsMQTT - Subscribing to all
deebotozmo DEBUG    [Command] SpotArea content=4 count=CLEANINGS
Traceback (most recent call last):
  File "/home/openhabian/.local/bin/deebotozmo", line 10, in <module>
    sys.exit(cli())
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/cli.py", line 106, in SpotArea
    vacbot.SpotArea(rooms, cleanings)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 605, in SpotArea
    self.exc_command('clean', {'act': 'start', 'content': str(area), 'count': int(cleanings), 'type': 'spotArea'})
ValueError: invalid literal for int() with base 10: 'CLEANINGS'
openhabian@PI100:~ $ deebotozmo  --debug spotarea 4 cleaning
deebotozmo DEBUG    Setting up EcoVacsAPI
deebotozmo DEBUG    calling main api user/login with (('account', 'ANg5RdMix7sRFRV75Z2DKkK3BaU6RYR1yEDsxUJzZwjNpiA5u1VR45SgisZ/B3xw7wdadudBQeg586rsBSJtfoNpmE1kB1tSe94BFstzr0E0nngxeuNpljOJ/BZ52h2SgooNBGRbO8pYTlbGjflhWzR8AaYjdu7fMgYFqnFqCZM='), ('password', 'y3gkOmYst6ly0kP9+3AHlUaYZ8KVtXpFbDkMkVOp9QH7wR6shE+bjh0hBErUj6ASsUqdyYAPMhD8lw6fkcq7sBL++Yzgg4ZvpWeYzCL3+rOWnCiw6DXIYbvC/doVbZ8VVFivUOgI8HDBjwh55pbEji1WcRmknrg6u04okO0cWGQ='))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1610988903434, 'data': {'uid': 'XXXXXXXXXXXXXXXXXXXX', 'username': 'YYYYYYY', 'email': 'YYYYYYY@xyz.com', 'country': 'in', 'accessToken': 'a76dddeb2e2931d45c5e0259908f8af6'}}
deebotozmo DEBUG    calling main api user/getAuthCode with (('uid', 'XXXXXXXXXXXXXXXXXXXX'), ('accessToken', 'a76dddeb2e2931d45c5e0259908f8af6'))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1610988904064, 'data': {'authCode': 'in_838599921c07cfc009cc3e6f2e87584d', 'ecovacsUid': 'ghdjftgsjhfgsjhgeuyfxckjvhxcuvxdvjhgh'}}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'userId': 'ghdjftgsjhfgsjhge', 'resource': '57ec159e', 'token': '0428fbd2f145404390b848bcb2ebafe8', 'last': 604800000}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'devices': [{'did': '0cb98872-0297-409e-b9b7-d5e0f1b00eb8', 'name': 'E093LCQP9B09HEJJ0244', 'class': 'yna5xi', 'resource': '3N0R', 'nick': 'eccho', 'company': 'eco-ng', 'bindTs': 1606409485695}]}
deebotozmo.ecovacsiotmq DEBUG    EcoVacsMQTT - Connected with result code 0
deebotozmo.ecovacsiotmq DEBUG    EcoVacsMQTT - Subscribing to all
deebotozmo DEBUG    [Command] SpotArea content=4 count=cleaning
Traceback (most recent call last):
  File "/home/openhabian/.local/bin/deebotozmo", line 10, in <module>
    sys.exit(cli())
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/openhabian/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/cli.py", line 106, in SpotArea
    vacbot.SpotArea(rooms, cleanings)
  File "/home/openhabian/.local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 605, in SpotArea
    self.exc_command('clean', {'act': 'start', 'content': str(area), 'count': int(cleanings), 'type': 'spotArea'})
ValueError: invalid literal for int() with base 10: 'cleaning'`

**Comment by sujitrp** [comment]
Hi, Am I doing some basic mistake ?

**Comment by And3rsL** [comment]
Maybe,
please try with:

`deebotozmo --debug spotarea 4
`

for more cleanings you need to use 

`deebotozmo --debug spotarea 4 2 <- this 2 means 2x cleanings
`

**Comment by sujitrp** [comment]
this is working 
 deebotozmo --debug spotarea 4 2
 deebotozmo --debug spotarea 4 1
this is working without debug / option 
 deebotozmo spotarea 4 2
