### ISSUE TITLE
After Updating to 2.0.0, state becomes unavailable when Robot starts Cleaning

### ISSUE THREAD

**Issue by LuckyTriple7** [And3rsL/Deebotozmo#26]
OZMO T8 AIVI

When the Robot starts cleaning, state becomes unavailable.
After Robot returns to dock, state changes to "docked" -> OK
Downgrading to V1.9.8: All is working fine.

`2021-01-26 19:32:54 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state changed for vacuum.eaad84cc_ce3a_4b89_b75e_ac95c65e0566
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 257, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 960, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 248, in _handle_results
    attr.handle_result(
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 87, in handle_result
    self.on_update(result)
  File "/usr/src/homeassistant/homeassistant/components/template/vacuum.py", line 388, in _update_battery_level
    battery_level_int = int(battery_level)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`

**Comment by LuckyTriple7** [comment]
Fixed with 2.0.1
Thx
