### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by Morg42** [And3rsL/Deebotozmo#6]
Just as a feedback: something went wrong, though I don't know, what. I can't see any limitations.

This time the ozmo was running; when the same exception occured yesterday, it was dozing in the charger.

```Exception in thread mqtt_schedule_thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/sched.py", line 147, in run
    action(*argument, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/deebotozmo/ecovacsiotmq.py", line 79, in _run_scheduled_func
    timer_function()
  File "/usr/local/lib/python3.5/dist-packages/deebotozmo/__init__.py", line 483, in refresh_liveMap
    self.exc_command('getMapTrace',{'pointCount':200,'traceStart':0})
  File "/usr/local/lib/python3.5/dist-packages/deebotozmo/__init__.py", line 573, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "/usr/local/lib/python3.5/dist-packages/deebotozmo/__init__.py", line 577, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "/usr/local/lib/python3.5/dist-packages/deebotozmo/ecovacsiotmq.py", line 115, in send_command
    self._handle_ctl_api(action, self.CallIOTApi(self.jsonRequestHeader(action, recipient) ,verify_ssl=self.verify_ssl ))
  File "/usr/local/lib/python3.5/dist-packages/deebotozmo/ecovacsiotmq.py", line 208, in _handle_ctl_api
    s(resp)
  File "/usr/local/lib/python3.5/dist-packages/deebotozmo/__init__.py", line 255, in _handle_ctl
    getattr(self, method)(ctl)
  File "/usr/local/lib/python3.5/dist-packages/deebotozmo/__init__.py", line 339, in _handle_map_trace
    self.__map.updateTracePoints(response['traceValue'])
KeyError: 'traceValue'```

**Comment by And3rsL** [comment]
should work now

**Comment by Morg42** [comment]
Thanks for the quick resolving. Didn't occur again, well done!
