### ISSUE TITLE
Auth fail

### ISSUE THREAD

**Issue by cagnulein** [And3rsL/Deebotozmo#7]
<pre>
cagnulein@localhost:~$ deebotozmo createconfig
Ecovacs app email: dsdsd@gmail.com
Ecovacs app password:
your two-letter country code [it]:
your two-letter continent code [eu]:
Verify SSL for API requests [True]:
Config saved.

cagnulein@localhost:~$ deebotozmo --debug statuses
deebotozmo DEBUG    Setting up EcoVacsAPI
deebotozmo DEBUG    calling main api user/login with (('account', 'XXXXXXXXXXXXXXXXXXX'), ('password', 'XXXXXXXXXXXXXXXXXXXXXX'))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1591279443360, 'data': {'uid': '20200501183011_696e37bcda0073107743af564f5736ce', 'username': 'XXXX', 'email': 'XXXX@gmail.com', 'country': 'it', 'accessToken': 'XXXXXX'}}
deebotozmo DEBUG    calling main api user/getAuthCode with (('uid', '20200501183011_696e37bcda0073107743af564f5736ce'), ('accessToken', 'XXXXX'))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1591279443888, 'data': {'authCode': 'XXXXXX', 'ecovacsUid': 'XXXXXX'}}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'userId': 'XXXX', 'resource': 'b9d09d05', 'token': 'XXXXXX', 'last': 604800000}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'devices': [{'did': '872eebc6-5799-4a09-9592-91b87278bc79', 'name': 'e2001213091900752092', 'class': 'dl8fht', 'resource': '2M2m', 'nick': None, 'company': 'eco-ng', 'bindTs': 1570385440359}, {'did': '1cc0fa0e-4a3e-47f9-a548-537fbc5c80ee', 'name': 'E0001344119603070569', 'class': '2pv572', 'resource': '0ZuT', 'nick': None, 'company': 'eco-ng', 'bindTs': 1590063655125}]}
deebotozmo.ecovacsiotmq DEBUG    EcoVacsMQTT - Connected with result code 0
deebotozmo.ecovacsiotmq DEBUG    EcoVacsMQTT - Subscribing to all
deebotozmo DEBUG    [refresh_statuses] Begin
deebotozmo.ecovacsiotmq DEBUG    1591279446.467571| calling IOT api with {'auth': {'realm': 'ecouser.net', 'resource': 'b9d09d05', 'token': 'XXXXX', 'userid': 'XXXXX', 'with': 'users'}, 'cmdName': 'getCleanInfo', 'payload': OrderedDict([('header', OrderedDict([('pri', '2'), ('ts', 1591279446.46751), ('tmz', 480), ('ver', '0.0.22')]))]), 'payloadType': 'j', 'td': 'q', 'toId': '872eebc6-5799-4a09-9592-91b87278bc79', 'toRes': '2M2m', 'toType': 'dl8fht'}
deebotozmo.ecovacsiotmq DEBUG    Timeout Error: HTTPSConnectionPool(host='portal-eu.ecouser.net', port=443): Read timed out. (read timeout=20)
Traceback (most recent call last):
  File "/home/cagnulein/.local/bin/deebotozmo", line 11, in <module>
    sys.exit(cli())
  File "/home/cagnulein/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/cagnulein/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/cagnulein/.local/lib/python3.6/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/cagnulein/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cagnulein/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/cagnulein/.local/lib/python3.6/site-packages/deebotozmo/cli.py", line 151, in statuses
    vacbot.refresh_statuses()
  File "/home/cagnulein/.local/lib/python3.6/site-packages/deebotozmo/__init__.py", line 475, in refresh_statuses
    self.exc_command('getCleanInfo')
  File "/home/cagnulein/.local/lib/python3.6/site-packages/deebotozmo/__init__.py", line 582, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "/home/cagnulein/.local/lib/python3.6/site-packages/deebotozmo/__init__.py", line 586, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "/home/cagnulein/.local/lib/python3.6/site-packages/deebotozmo/ecovacsiotmq.py", line 115, in send_command
    self._handle_ctl_api(action, self.CallIOTApi(self.jsonRequestHeader(action, recipient) ,verify_ssl=self.verify_ssl ))
  File "/home/cagnulein/.local/lib/python3.6/site-packages/deebotozmo/ecovacsiotmq.py", line 216, in _handle_ctl_api
    if 'resp' in message:
TypeError: argument of type 'NoneType' is not iterable
</pre>

**Comment by cagnulein** [comment]
@And3rsL did you have a chance to look into it?

**Comment by cagnulein** [comment]
this one works https://github.com/Ligio/hacc-ozmo with my setup

**Comment by sujitrp** [comment]
Update numpy

**Comment by edenhaus** [comment]
```
File "/home/cagnulein/.local/lib/python3.6/site-packages/deebotozmo/ecovacsiotmq.py", line 216, in _handle_ctl_api
    if 'resp' in message:
TypeError: argument of type 'NoneType' is not iterable
```
This error is already fixed. Can you retry and give us feedback.

**Comment by cagnulein** [comment]
ups i didn't check this. I will try and i will give you a feedback

**Comment by cagnulein** [comment]
i've tried now with the last version and i got this error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/deebot/vacuum.py", line 230, in device_state_attributes
    data['status'] = STATE_CODE_TO_STATE[self.device.vacuum_status]
KeyError: None
