### ISSUE TITLE
key error continent, I'm in Aus and put in ww for continent 🤷

### ISSUE THREAD

**Issue by valtoree** [And3rsL/Deebotozmo#72]
As above, recently installed deebotozmo,
Did createconfig
And then tried deebotozmo stats, dumps a whole lot of data at end says
KeyError: 'continent' 🤷

Please help
Regards

**Comment by edenhaus** [comment]
Please provide more information's and logs. Which version are you using?
Also the steps how we can recreate your issue.

**Comment by valtoree** [comment]
Tx 4 reply, deebotozmo 3.0.0.
Using majaro xfce, just did a pip install deebotozmo.
Full error output after doing : deebotozmo stats. Naturally did deebotozmo createconfig before the stats command.

Full error log:

Traceback (most recent call last):
  File "/home/red/.local/bin/deebotozmo", line 8, in <module>
    sys.exit(cli())
  File "/home/red/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/red/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/red/.local/lib/python3.9/site-packages/click/core.py", line 1699, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/red/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/red/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/red/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/red/.local/lib/python3.9/site-packages/deebotozmo/cli.py", line 49, in wrapper
    return loop.run_until_complete(func(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/red/.local/lib/python3.9/site-packages/deebotozmo/cli.py", line 349, in stats
    util = CliUtil()
  File "/home/red/.local/lib/python3.9/site-packages/deebotozmo/cli.py", line 492, in __init__
    self._continent = config["continent"]
  File "/usr/lib/python3.9/configparser.py", line 1257, in __getitem__
    raise KeyError(key)
KeyError: 'continent'
