### ISSUE TITLE
command deebotozmo getrooms doesn't work

### ISSUE THREAD

**Issue by valtoree** [And3rsL/Deebotozmo#85]
running manjaro xfce, I had reported earlier about command creatconfig not working and that was fixed so thanks.

Now getting another error on command 'getrooms'.

Using Ozmo 920

Full error output:
asyncio    ERROR    Task exception was never retrieved
future: <Task finished name='Task-10' coro=<EventEmitter._call_refresh_function() done, defined at /home/yogi/.local/lib/python3.9/site-packages/deebotozmo/event_emitter.py:97> exception=RuntimeError('Session is closed')>
Traceback (most recent call last):
  File "/home/yogi/.local/lib/python3.9/site-packages/deebotozmo/event_emitter.py", line 104, in _call_refresh_function
    await self._refresh_function()
  File "/home/yogi/.local/lib/python3.9/site-packages/deebotozmo/util.py", line 42, in refresh
    await execute_command(commands[0])
  File "/home/yogi/.local/lib/python3.9/site-packages/deebotozmo/vacuum_bot.py", line 147, in execute_command
    response = await self.json.send_command(command, self.vacuum)
  File "/home/yogi/.local/lib/python3.9/site-packages/deebotozmo/ecovacs_json.py", line 47, in send_command
    async with self._session.post(
  File "/home/yogi/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/yogi/.local/lib/python3.9/site-packages/aiohttp/client.py", line 381, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

**Comment by edenhaus** [comment]
I will fix it tomorrow.

**Comment by schwatter** [comment]
Sorry for answering in an closed mr. I thought it is the right place because of the fast progress by you. All infos about the cli progress is there. Next time i open a new issue or pull.
Can you please look also at the map. It is also broken.

Thx

**Comment by edenhaus** [comment]
Sorry but maintaining the general part of the library is already time consuming and I do this all in my freetime… I have not the time to maintain also the cli.

Also please notice that in nearly all (open source) projects, there is a one bug one issue rule. So please open a new issue for the map bug.

Short update on the map functionality: 
Currently map events will not be thrown as Home Assistant is calling the function repeatedly if a user is currently watching a map. The event subscriber will only be checked, to verify if we need to parsed the received message or not. 
I currently have no plans to change it as it works for me as I’m a Home Assistant user. As always feel free to open a PR

The cli is using polling and not mqtt to get asynchron messages. I also don’t now if you can get asynchron messages with a cli. I see the cli more as test tool and not ready for production use.

**Comment by schwatter** [comment]
For the cli we don't need asynchron messages. I know your claim is a lot of higher as you did a big rewrite if the library. But let the small users die like me.

**Comment by edenhaus** [comment]
@schwatter btw instead of writing comments with code that fixes the problem and wondering that rany2 was not responding, you can directly create a PR with the fix. This will help all and the fix will be merged sooner
